apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config-{{number}}
data:
  node-script: |
    - !Wait
      time: 100s

---

apiVersion: batch/v1
kind: Job
metadata:
  name: node-{{number}}-job
spec:
  template:
    spec:
      containers:
      - name: eon-client
        image: 10.1.1.18:5000/eon-client
        command: [
          "eon-client",
          "--stdout",
          "--log-level", "debug",
          "--bootstrap-addr", "10.96.0.100",
          "--script-path", "/mnt/scripts/script.yaml",
          "--delay", "{{delay}}"
        ]
        volumeMounts:
        - name: scripts
          mountPath: "/mnt/scripts"
          readOnly: true
      volumes:
      - name: scripts
        configMap:
          name: node-config-{{number}}
          items:
          - key: "node-script"
            path: "script.yaml"
      restartPolicy: Never
  backoffLimit: 4
