apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-config
data:
  publish-script: |
    - !Wait
      time: 4m
    - !Publish
      path: /mnt/scripts/test.txt
    - !Wait
      time: 30m
  test-file: Hello

---

apiVersion: batch/v1
kind: Job
metadata:
  name: provider-job
spec:
  template:
    spec:
      containers:
      - name: eon-client
        image: 10.1.1.18:5000/eon-client
        command: [
          "eon-client",
          "--stdout",
          "--log-level", "debug",
          "--bootstrap-addr", "10.96.0.100",
          "--secret-key-seed", "12",
          "--script-path", "/mnt/scripts/script.yaml",
          "--delay", "{{delay}}"
        ]
        volumeMounts:
        - name: scripts
          mountPath: "/mnt/scripts"
          readOnly: true
      volumes:
      - name: scripts
        configMap:
          name: provider-config
          items:
          - key: "publish-script"
            path: "script.yaml"
          - key: "test-file"
            path: "test.txt"
      restartPolicy: Never
  backoffLimit: 4
